services:
  poc-postgres:
    image: postgres:latest
    container_name: poc-db
    environment:
      POSTGRES_USER: pocuserpg
      POSTGRES_PASSWORD: pocpasspg
      POSTGRES_DB: pocdb
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  poc-mongo:
    image: mongo:4.2
    container_name: poc-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres-data:
  mongo_data: