services:
  poc-postgres:
    image: postgres:12
    container_name: poc-db
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
      POSTGRES_DB: poc
    ports:
      - "5424:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  poc-mongo:
    image: mongo:4.2
    container_name: poc-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:

networks:
  poc-network:
    driver: bridge