# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  # TODO: Change variable to your image's name.
  # IMAGE_NAME: gemii-idle-game-api
  REGISTRY_NAME: tcoinproject
  HOME: /root

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install doctl                 # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build image frontend
        run: |
          cd ./frontend
          docker build . --file Dockerfile --tag nitmx-poc-frontend --build-arg NODE_OPTIONS=--max-old-space-size=3500

      - name: Build image backend
        run: |
          cd ./backend
          docker build . --file Dockerfile --tag nitmx-poc-backend --build-arg NODE_OPTIONS=--max-old-space-size=3500


      - name: Push image
        run: |
          doctl registry login --expiry-seconds 1200
          docker tag nitmx-poc-frontend registry.digitalocean.com/$REGISTRY_NAME/nitmx-poc-frontend
          docker tag nitmx-poc-backend registry.digitalocean.com/$REGISTRY_NAME/nitmx-poc-backend
          docker push registry.digitalocean.com/$REGISTRY_NAME/nitmx-poc-frontend
          docker push registry.digitalocean.com/$REGISTRY_NAME/nitmx-poc-backend

      - name: Update deployment file
        if: github.ref == 'refs/heads/main'
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<BUILD_TAG>|'${TAG}'|' $GITHUB_WORKSPACE/deployment.yaml
          cat $GITHUB_WORKSPACE/deployment.yaml

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        # if: github.ref == 'refs/heads/main'
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 6000 k8s-1-30-1-do-0-sgp1-1719331222191

      - uses: azure/setup-kubectl@v1
        # if: github.ref == 'refs/heads/main'
        with:
          version: 'v1.16.2' # default is latest stable
        id: install

      - name: Deploy to DigitalOcean Kubernetes
        # if: github.ref == 'refs/heads/main'
        run: kubectl apply -f $GITHUB_WORKSPACE/deployment.yaml

      - name: Verify deployment
        # if: github.ref == 'refs/heads/main'
        run: |
          kubectl rollout status deployment/nitmx-poc-frontend
          kubectl rollout status deployment/nitmx-poc-backend
